// Official CLI v1.0.96 workspace/identity overrides. Installation and the
// generated native skill must select the same CLI workspace and credentials.
export const LARK_BUSINESS_CLEARED_ENV = [
  'OPENCLAW_HOME', 'OPENCLAW_CLI', 'OPENCLAW_STATE_DIR', 'OPENCLAW_CONFIG_PATH',
  'OPENCLAW_SERVICE_MARKER', 'OPENCLAW_SERVICE_VERSION', 'OPENCLAW_GATEWAY_PORT', 'OPENCLAW_SHELL',
  'HERMES_HOME', 'HERMES_QUIET', 'HERMES_EXEC_ASK', 'HERMES_GATEWAY_TOKEN', 'HERMES_SESSION_KEY',
  'LARK_CHANNEL',
  'LARKSUITE_CLI_APP_ID', 'LARKSUITE_CLI_APP_SECRET', 'LARKSUITE_CLI_BRAND',
  'LARKSUITE_CLI_USER_ACCESS_TOKEN', 'LARKSUITE_CLI_TENANT_ACCESS_TOKEN',
  'LARKSUITE_CLI_TENANT_ACCESS_TOKEN_SOURCE', 'LARKSUITE_CLI_DEFAULT_AS',
  'LARKSUITE_CLI_PROFILE', 'LARKSUITE_CLI_STRICT_MODE',
  'LARKSUITE_CLI_AUTH_PROXY', 'LARKSUITE_CLI_PROXY_KEY', 'LARKSUITE_CLI_CONTENT_SAFETY_MODE',
  'LARKSUITE_CLI_AGENT_NAME', 'LARKSUITE_CLI_AGENT_TRACE',
  'LARKSUITE_CLI_PROXY_ENABLE', 'LARKSUITE_CLI_PROXY_ADDRESS', 'LARKSUITE_CLI_CA_PATH',
] as const
